### ISSUE TITLE
Moving the project to a separate organization

### ISSUE THREAD

**Issue by boynux** [tenpureto/tenpureto#18]
Hi

I created the `tenpureto` github org and assigned @rtimush as the owner. It's good if we move the project to this new organization

**Comment by rtimush** [comment]
At the moment, I doubt moving to a separate organization because I would like to be able to use GitHub Actions and they are not yet available in there. By the time the project grows into multiple repositories, I hope actions will be already available and this won't be a blocker anymore.
Do you see any particular benefits in moving now?

**Comment by boynux** [comment]
Having a separate org makes it easier for external contributions and adding
more maintainers is also easier.
I was also thinking about setting up a Github pages to host a small website
and docs for the project to make it easier for teams to get started with it.

I was not aware of using Github Actions for the project. I'll keep the org
and once it's feasible we can move it there.

**Comment by rtimush** [comment]
Moved to https://github.com/tenpureto
