### ISSUE TITLE
Rely on completely empty directory

### ISSUE THREAD

**Issue by omakoleg** [tenpureto/tenpureto#38]
Expected behaviour is to ignore all dot-files like `.git` etc.
But instead giving error:
```
tenpureto: user error (Directory is not empty)
```

**Comment by rtimush** [comment]
`tenpureto` doesn’t make any special assumptions about filenames - the template can contain files starting with a dot, and `.git` will be definitely overwritten. Overwriting existing files feels dangerous, therefore I check if the target directory is empty.

**Comment by omakoleg** [comment]
Could be `.git` added as exception and not touched by tool at all. 
(1) create github repository,
(2) clone it locally, 
(3) run tenpureto to generate project.It shows me error.

But this flow is pretty common

**Comment by rtimush** [comment]
`tenpureto` creates a git repository by design, so it has to touch `.git`. Not sure if I fully understand the workflow, can you please share some more details about what you want to achieve? If you want to use the GitHub repository from the step (1) as a template then you don't need to clone it. If you want to use the local clone as a template, then you probably don't want to override the clone and will create your project at some other location.

**Comment by omakoleg** [comment]
Could you explain why `tenpureto` needs to touch `.git` and could this be omitted?
Need it for case when creating project with `tenpureto` on existing repository or subfolder.

**Comment by rtimush** [comment]
Currently, `tenpureto` always creates a new git repository, the case of scaffolding into an existing repository (to the root or a subfolder) is not supported yet. I have created #45 to cover this use case, is it what you've been looking for?

**Comment by omakoleg** [comment]
yes
